"use strict";
const $=s=>document.querySelector(s);let csrf="";
async function csrfToken(){const r=await fetch("/api/csrf",{credentials:"same-origin",cache:"no-store"});if(!r.ok)throw Error("Security session unavailable");csrf=(await r.json()).csrf_token||"";return csrf;}
async function api(url,opt={}){const method=(opt.method||"GET").toUpperCase();const headers=new Headers(opt.headers||{});if(method!=="GET"&&method!=="HEAD"){await csrfToken();headers.set("X-CSRF-Token",csrf);}const r=await fetch(url,{...opt,method,headers,credentials:"same-origin",cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||`Request failed (${r.status})`);return d;}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function msg(t,e=false){const el=$("#msg");el.textContent=t||"";el.classList.toggle("error",e);}
async function load(){try{const [o,u,a]=await Promise.all([api("/api/admin/overview"),api("/api/admin/users"),api("/api/admin/audit")]);const cards=$("#stats").querySelectorAll("strong");cards[0].textContent=o.users;cards[1].textContent=o.recordings;cards[2].textContent=o.audit_events;$("#users").innerHTML=u.length?u.map(x=>`<tr><td><strong>${esc(x.username)}</strong><small>#${x.id}</small></td><td>${esc(x.email||"—")}</td><td>${esc(new Date(x.created_at).toLocaleString())}</td><td>${x.recordings}</td><td><span class="role ${x.is_admin?"admin":"user"}">${x.is_admin?"ADMIN":"USER"}</span></td><td>${x.is_admin?"":"<button class=\"delete-user\" data-id=\""+String(x.id)+"\" type=\"button\">DELETE</button>"}</td></tr>`).join(""):"<tr><td colspan=6>No users.</td></tr>";$("#audit").innerHTML=a.length?a.map(x=>`<tr><td>${esc(new Date(x.created_at).toLocaleString())}</td><td>${esc(x.user_id??"—")}</td><td><strong>${esc(x.action)}</strong></td><td>${esc(x.detail||"—")}</td><td>${esc(x.ip||"—")}</td></tr>`).join(""):"<tr><td colspan=5>No audit events.</td></tr>";}catch(e){console.error("GhostVoice admin load failed",e);msg(e.message,true);if(e.message.includes("Administrator"))setTimeout(()=>location.href="/",1200);}}
$("#refresh").addEventListener("click",load);
$("#users").addEventListener("click",async e=>{const b=e.target.closest(".delete-user");if(!b)return;const id=String(b.dataset.id||"").trim();if(!/^\d+$/.test(id)){msg("Invalid user ID.",true);return;}if(!confirm("Delete this account and all of its saved encrypted audios? This cannot be undone."))return;b.disabled=true;b.textContent="DELETING…";try{const result=await api(`/api/admin/users/${id}/delete`,{method:"POST"});msg(`Account deleted. ${result.deleted_recordings||0} encrypted recording(s) removed.`);await load();}catch(err){console.error("GhostVoice admin delete failed",err);msg(err.message,true);b.disabled=false;b.textContent="DELETE";}});
$("#logout").addEventListener("click",async()=>{try{await api("/api/logout",{method:"POST"});location.href="/";}catch(e){msg(e.message,true);}});load();
